<?php

function guides_helpers_menu()
{
	$items["guides/redirect"]=array(
		"access arguments"=>array("edit own guide content"),
		"page callback"=>"guides_helpers_redirect",
		"type"=>MENU_CALLBACK
	);

	return $items;
}


function guides_helpers_rules_action_info() {
  return array(
    'guides_helpers_publish_action' => array(
      'label' => t('Publish guide card'),
      'arguments' => array(
        'user' => array('type' => 'user', 'label' => t('Current user')),
      ),
      'module' => 'User',
    )
  );
}

function guides_helpers_publish_action($user)
{
	if(isset($user->uid))
	{
		$uid=$user->uid;
	}
	else
	{
		$uid=$context['uid'];
	}

   db_query("UPDATE {node} SET status = 1 WHERE uid = %d AND type='guide'", $uid);
   watchdog('action', 'Published guide card for guide %uid', array('%uid' => $uid));
}

function guides_helpers_get_card($account=null)
{
	static $nids;
	if(!$account)
	{
		global $user;
		$account=$user;
	}
	if(!isset($nids[$account->uid]))
		$nids[$account->uid]=db_result(db_query("SELECT nid FROM {node} WHERE uid=%d AND type='guide'", $account->uid));
	return $nids[$account->uid];
}

function guides_helpers_redirect()
{
	if($nid=guides_helpers_get_card())
	{
		$path="node/".$nid;
	}
	else
	{
		$path=drupal_get_normal_path(variable_get('site_frontpage', 'node'));
	}
	drupal_goto($path);
}

function guides_helpers_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL)
{
	if($node->type=="testimonial" && $op=="view" && $a4)
	{
		$node->guide=node_load($node->field_guide[0]["nid"]);
	}
}

function guides_helpers_form_alter(&$form, &$form_state, $form_id)
{
	if($form_id=="guide_node_form")
	{
		if($nid=guides_helpers_get_card())
		{
			drupal_set_message("У вас уже есть карточка гида, вот она", "error");
			drupal_goto("node/".$nid);
		}
	}
}